name: Mining
main: me.pjr8.Main
version: '0.1 Development'
api-version: '1.20'
commands:
  item:
    description: Item
  admin:
    description: Admin mode
  test:
    description: Test
  rank:
    description: Rank
  pickaxeupgrade:
    description: Pickaxe Upgrade
  forge:
    description: Forge